export enum ActionType {
  AUTH_USER = 'auth_user',
  AUTH_USER_SUCCESS = 'auth_user_success',
  AUTH_USER_ERROR = 'auth_user_error',
  SIGN_OUT = 'sign_out',
  FETCH_CURRENT_USER = 'fetch_current_user',
  FETCH_USERS = 'fetch_users',
  FETCH_VIDEOS = 'fetch_videos',
  FETCH_VIDEOS_SUCCESS = 'fetch_videos_success',
  FETCH_VIDEOS_ERROR = 'fetch_videos_error',
  FETCH_ALL_VIDEOS = 'fetch_all_videos',
  LIKE_VIDEO = 'like_video',
  SUBSCRIBE_USER = 'subscribe_user',
  UNSUBSCRIBE_USER = 'unsubscribe_user',
  CREATE_VIDEO = 'create_video',
  FETCH_RECOMMENDATIONS = 'fetch_recommendations',
  SHOW_POPUP = 'show_popup',
}
